# Generated by Django 2.2.5 on 2020-09-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset_vuejs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_formset_vuejs.AuthorContainer'),
        ),
    ]
