[tool.poetry]
name = "dataiku"
version = "0.1.0"
description = ""
authors = ["Your Name <cbeltran@umanis.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
