# Generated by Django 2.2.5 on 2020-08-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataiku_account',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('in operation', 'in operation'), ('avaible', 'avaible')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LearningPathUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('LearningPathName', models.CharField(blank=True, max_length=255, null=True)),
                ('CourseUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('CourseName', models.CharField(blank=True, max_length=255, null=True)),
                ('QcmUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('QcmName', models.CharField(blank=True, max_length=255, null=True)),
                ('Lenght', models.IntegerField(default=0)),
                ('Verif', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('text', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('check', 'check')], max_length=255, null=True)),
                ('choice_type', models.CharField(blank=True, choices=[('checkbox', 'checkbox'), ('radio', 'radio')], default='radio', max_length=255, null=True)),
                ('max_choices', models.IntegerField(default=0)),
                ('cursor', models.IntegerField(default=1)),
                ('qcm_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.QCM')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=510, null=True)),
                ('supertask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(editable=False)),
                ('countdown', models.CharField(blank=True, default='59:59', max_length=10, null=True)),
                ('score', models.IntegerField(default=0)),
                ('lenght', models.IntegerField(default=0)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.Dataiku_account')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('question_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.Question')),
                ('session_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Posibility',
            fields=[
                ('text', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, null=True)),
                ('question_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(editable=False)),
                ('statut', models.CharField(blank=True, choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done')], max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataiku.Dataiku_account')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Posibility')),
                ('connected_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Run')),
            ],
        ),
    ]
