# Generated by Django 2.2.5 on 2020-08-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataiku_account',
            name='task',
        ),
    ]
