# Generated by Django 2.2.5 on 2020-08-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0002_remove_dataiku_account_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.AddField(
            model_name='question',
            name='max_choices',
            field=models.IntegerField(default=0),
        ),
    ]
