# Generated by Django 2.2.5 on 2020-08-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0003_remove_answer2_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer2',
            name='connected_run',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Answer2',
        ),
    ]
