# Generated by Django 2.2.5 on 2020-08-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0004_auto_20200829_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='posibility',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='run',
            new_name='connected_run',
        ),
    ]
