# Generated by Django 2.2.5 on 2020-08-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0005_auto_20200829_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posibility',
            old_name='question',
            new_name='question_link',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qcm',
            new_name='qcm_link',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='question',
            new_name='question_link',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='session',
            new_name='session_link',
        ),
    ]
