# Generated by Django 2.2.5 on 2020-09-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Posibility'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='connected_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataiku.Run'),
        ),
    ]
