# Generated by Django 2.2.5 on 2020-08-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0006_auto_20200829_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
