# Generated by Django 2.2.5 on 2020-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataiku', '0008_auto_20200829_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posibility',
            name='id',
        ),
        migrations.AlterField(
            model_name='posibility',
            name='text',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
