# Generated by Django 2.2.5 on 2020-08-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QQM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LearningPathUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('LearningPathName', models.CharField(blank=True, max_length=255, null=True)),
                ('CourseUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('CourseName', models.CharField(blank=True, max_length=255, null=True)),
                ('QcmUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('QcmName', models.CharField(blank=True, max_length=255, null=True)),
                ('Lenght', models.IntegerField(default=0)),
                ('Verif', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_formset_vuejs.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_formset_vuejs.AuthorContainer'),
        ),
    ]
