# Generated by Django 2.2.5 on 2020-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset_vuejs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QQM',
            new_name='QCM',
        ),
    ]
