# Generated by Django 2.2.5 on 2020-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formset_vuejs', '0002_auto_20200906_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
